# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(778, 706)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 30, 511, 105))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_nICs = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nICs.sizePolicy().hasHeightForWidth())
        self.label_nICs.setSizePolicy(sizePolicy)
        self.label_nICs.setObjectName("label_nICs")
        self.gridLayout.addWidget(self.label_nICs, 1, 0, 1, 1)
        self.label_tsteps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tsteps.setObjectName("label_tsteps")
        self.gridLayout.addWidget(self.label_tsteps, 3, 0, 1, 1)
        self.labe_nclus = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labe_nclus.sizePolicy().hasHeightForWidth())
        self.labe_nclus.setSizePolicy(sizePolicy)
        self.labe_nclus.setObjectName("labe_nclus")
        self.gridLayout.addWidget(self.labe_nclus, 1, 1, 1, 1)
        self.spinBox_nICs = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_nICs.setMinimum(3)
        self.spinBox_nICs.setMaximum(10)
        self.spinBox_nICs.setObjectName("spinBox_nICs")
        self.gridLayout.addWidget(self.spinBox_nICs, 2, 0, 1, 1)
        self.label_tcut = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tcut.setObjectName("label_tcut")
        self.gridLayout.addWidget(self.label_tcut, 3, 1, 1, 1)
        self.lineEdit_tcut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tcut.setObjectName("lineEdit_tcut")
        self.gridLayout.addWidget(self.lineEdit_tcut, 4, 1, 1, 1)
        self.spinBox_nclus = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_nclus.setMinimum(3)
        self.spinBox_nclus.setObjectName("spinBox_nclus")
        self.gridLayout.addWidget(self.spinBox_nclus, 2, 1, 1, 1)
        self.lineEdit_tstep = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tstep.setObjectName("lineEdit_tstep")
        self.gridLayout.addWidget(self.lineEdit_tstep, 4, 0, 1, 1)
        self.lineEdit_numneurons = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_numneurons.setObjectName("lineEdit_numneurons")
        self.gridLayout.addWidget(self.lineEdit_numneurons, 4, 2, 1, 1)
        self.label_numneurons = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_numneurons.setObjectName("label_numneurons")
        self.gridLayout.addWidget(self.label_numneurons, 3, 2, 1, 1)
        self.label_vcut = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vcut.setObjectName("label_vcut")
        self.gridLayout.addWidget(self.label_vcut, 1, 2, 1, 1)
        self.lineEdit_vcut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vcut.setObjectName("lineEdit_vcut")
        self.gridLayout.addWidget(self.lineEdit_vcut, 2, 2, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 160, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_dff = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dff.sizePolicy().hasHeightForWidth())
        self.pushButton_dff.setSizePolicy(sizePolicy)
        self.pushButton_dff.setObjectName("pushButton_dff")
        self.verticalLayout_2.addWidget(self.pushButton_dff)
        self.pushButton_noise = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_noise.sizePolicy().hasHeightForWidth())
        self.pushButton_noise.setSizePolicy(sizePolicy)
        self.pushButton_noise.setObjectName("pushButton_noise")
        self.verticalLayout_2.addWidget(self.pushButton_noise)
        self.pushButton_ica = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ica.sizePolicy().hasHeightForWidth())
        self.pushButton_ica.setSizePolicy(sizePolicy)
        self.pushButton_ica.setObjectName("pushButton_ica")
        self.verticalLayout_2.addWidget(self.pushButton_ica)
        self.pushButton_kmeans = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kmeans.sizePolicy().hasHeightForWidth())
        self.pushButton_kmeans.setSizePolicy(sizePolicy)
        self.pushButton_kmeans.setObjectName("pushButton_kmeans")
        self.verticalLayout_2.addWidget(self.pushButton_kmeans)
        self.pushButton_pcas = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pcas.sizePolicy().hasHeightForWidth())
        self.pushButton_pcas.setSizePolicy(sizePolicy)
        self.pushButton_pcas.setObjectName("pushButton_pcas")
        self.verticalLayout_2.addWidget(self.pushButton_pcas)
        self.pushButton_regress = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_regress.sizePolicy().hasHeightForWidth())
        self.pushButton_regress.setSizePolicy(sizePolicy)
        self.pushButton_regress.setObjectName("pushButton_regress")
        self.verticalLayout_2.addWidget(self.pushButton_regress)
        self.pushButton_display = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_display.sizePolicy().hasHeightForWidth())
        self.pushButton_display.setSizePolicy(sizePolicy)
        self.pushButton_display.setObjectName("pushButton_display")
        self.verticalLayout_2.addWidget(self.pushButton_display)
        self.label_figh = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_figh.setObjectName("label_figh")
        self.verticalLayout_2.addWidget(self.label_figh)
        self.lineEdit_figh = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_figh.setObjectName("lineEdit_figh")
        self.verticalLayout_2.addWidget(self.lineEdit_figh)
        self.label_figw = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_figw.setObjectName("label_figw")
        self.verticalLayout_2.addWidget(self.label_figw)
        self.lineEdit_figw = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_figw.setObjectName("lineEdit_figw")
        self.verticalLayout_2.addWidget(self.lineEdit_figw)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(210, 590, 511, 89))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_loaddata = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loaddata.sizePolicy().hasHeightForWidth())
        self.pushButton_loaddata.setSizePolicy(sizePolicy)
        self.pushButton_loaddata.setObjectName("pushButton_loaddata")
        self.gridLayout_2.addWidget(self.pushButton_loaddata, 0, 0, 1, 1)
        self.lineEdit_data = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_data.setText("")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout_2.addWidget(self.lineEdit_data, 0, 1, 1, 1)
        self.pushButton_loadreg = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_loadreg.setObjectName("pushButton_loadreg")
        self.gridLayout_2.addWidget(self.pushButton_loadreg, 1, 0, 1, 1)
        self.lineEdit_regress = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_regress.setObjectName("lineEdit_regress")
        self.gridLayout_2.addWidget(self.lineEdit_regress, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(210, 150, 511, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 501, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mpl_signal = MatplotlibWidget(self.verticalLayoutWidget_4)
        self.mpl_signal.setObjectName("mpl_signal")
        self.verticalLayout_4.addWidget(self.mpl_signal)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_expsig = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_expsig.setObjectName("pushButton_expsig")
        self.horizontalLayout_2.addWidget(self.pushButton_expsig)
        self.lineEdit_expsig = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_expsig.setObjectName("lineEdit_expsig")
        self.horizontalLayout_2.addWidget(self.lineEdit_expsig)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl_analysis = MatplotlibWidget(self.verticalLayoutWidget)
        self.mpl_analysis.setObjectName("mpl_analysis")
        self.verticalLayout.addWidget(self.mpl_analysis)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_expana = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_expana.setObjectName("pushButton_expana")
        self.horizontalLayout.addWidget(self.pushButton_expana)
        self.lineEdit_expana = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_expana.setObjectName("lineEdit_expana")
        self.horizontalLayout.addWidget(self.lineEdit_expana)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.gridLayoutWidget_2.raise_()
        self.tabWidget.raise_()
        self.mpl_signal.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_nICs.setText(_translate("Form", "# of ICs"))
        self.label_tsteps.setText(_translate("Form", "time step (s)"))
        self.labe_nclus.setText(_translate("Form", "# of clusters"))
        self.label_tcut.setText(_translate("Form", "time_cutoff (s)"))
        self.lineEdit_tcut.setText(_translate("Form", "10.0"))
        self.lineEdit_tstep.setText(_translate("Form", "0.50"))
        self.lineEdit_numneurons.setText(_translate("Form", "100, 200"))
        self.label_numneurons.setText(_translate("Form", "# of neurons to show"))
        self.label_vcut.setText(_translate("Form", "var_cut"))
        self.lineEdit_vcut.setText(_translate("Form", "0.95"))
        self.pushButton_dff.setText(_translate("Form", "DF/F calculation"))
        self.pushButton_noise.setText(_translate("Form", "Noise level"))
        self.pushButton_ica.setText(_translate("Form", "ICA"))
        self.pushButton_kmeans.setText(_translate("Form", "Kmeans"))
        self.pushButton_pcas.setText(_translate("Form", "PCA-sort"))
        self.pushButton_regress.setText(_translate("Form", "Regression"))
        self.pushButton_display.setText(_translate("Form", "Show signal"))
        self.label_figh.setText(_translate("Form", "Figure height (in)"))
        self.lineEdit_figh.setText(_translate("Form", "7"))
        self.label_figw.setText(_translate("Form", "Figure width (in)"))
        self.lineEdit_figw.setText(_translate("Form", "7"))
        self.pushButton_loaddata.setText(_translate("Form", "Load data"))
        self.pushButton_loadreg.setText(_translate("Form", "Load regressor"))
        self.pushButton_expsig.setText(_translate("Form", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Signal cleaning"))
        self.pushButton_expana.setText(_translate("Form", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Clustering"))

from matplotlibwidget import MatplotlibWidget
