# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 706)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 30, 511, 105))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_tsteps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tsteps.setObjectName("label_tsteps")
        self.gridLayout.addWidget(self.label_tsteps, 3, 0, 1, 1)
        self.label_nICs = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nICs.sizePolicy().hasHeightForWidth())
        self.label_nICs.setSizePolicy(sizePolicy)
        self.label_nICs.setObjectName("label_nICs")
        self.gridLayout.addWidget(self.label_nICs, 1, 0, 1, 1)
        self.labe_nclus = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labe_nclus.sizePolicy().hasHeightForWidth())
        self.labe_nclus.setSizePolicy(sizePolicy)
        self.labe_nclus.setObjectName("labe_nclus")
        self.gridLayout.addWidget(self.labe_nclus, 1, 1, 1, 1)
        self.spinBox_nICs = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_nICs.setObjectName("spinBox_nICs")
        self.gridLayout.addWidget(self.spinBox_nICs, 2, 0, 1, 1)
        self.label_tcut = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tcut.setObjectName("label_tcut")
        self.gridLayout.addWidget(self.label_tcut, 3, 1, 1, 1)
        self.lineEdit_tcut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tcut.setObjectName("lineEdit_tcut")
        self.gridLayout.addWidget(self.lineEdit_tcut, 4, 1, 1, 1)
        self.spinBox_nclus = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_nclus.setObjectName("spinBox_nclus")
        self.gridLayout.addWidget(self.spinBox_nclus, 2, 1, 1, 1)
        self.lineEdit_tstep = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tstep.setObjectName("lineEdit_tstep")
        self.gridLayout.addWidget(self.lineEdit_tstep, 4, 0, 1, 1)
        self.label_tstims = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tstims.setObjectName("label_tstims")
        self.gridLayout.addWidget(self.label_tstims, 1, 2, 1, 1)
        self.lineEdit_stims = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_stims.setObjectName("lineEdit_stims")
        self.gridLayout.addWidget(self.lineEdit_stims, 2, 2, 1, 1)
        self.lineEdit_numneurons = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_numneurons.setObjectName("lineEdit_numneurons")
        self.gridLayout.addWidget(self.lineEdit_numneurons, 4, 2, 1, 1)
        self.label_numneurons = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_numneurons.setObjectName("label_numneurons")
        self.gridLayout.addWidget(self.label_numneurons, 3, 2, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 160, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_ica = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ica.sizePolicy().hasHeightForWidth())
        self.pushButton_ica.setSizePolicy(sizePolicy)
        self.pushButton_ica.setObjectName("pushButton_ica")
        self.verticalLayout_2.addWidget(self.pushButton_ica)
        self.pushButton_kmeans = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kmeans.sizePolicy().hasHeightForWidth())
        self.pushButton_kmeans.setSizePolicy(sizePolicy)
        self.pushButton_kmeans.setObjectName("pushButton_kmeans")
        self.verticalLayout_2.addWidget(self.pushButton_kmeans)
        self.pushButton_pcas = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pcas.sizePolicy().hasHeightForWidth())
        self.pushButton_pcas.setSizePolicy(sizePolicy)
        self.pushButton_pcas.setObjectName("pushButton_pcas")
        self.verticalLayout_2.addWidget(self.pushButton_pcas)
        self.pushButton_trigger = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_trigger.sizePolicy().hasHeightForWidth())
        self.pushButton_trigger.setSizePolicy(sizePolicy)
        self.pushButton_trigger.setObjectName("pushButton_trigger")
        self.verticalLayout_2.addWidget(self.pushButton_trigger)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(210, 140, 511, 441))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mpl_dff = MatplotlibWidget(self.verticalLayoutWidget_4)
        self.mpl_dff.setObjectName("mpl_dff")
        self.verticalLayout_4.addWidget(self.mpl_dff)
        self.mpl_analysis = MatplotlibWidget(self.verticalLayoutWidget_4)
        self.mpl_analysis.setObjectName("mpl_analysis")
        self.verticalLayout_4.addWidget(self.mpl_analysis)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 590, 511, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_load = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load.sizePolicy().hasHeightForWidth())
        self.pushButton_load.setSizePolicy(sizePolicy)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.lineEdit_protocol = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_protocol.setObjectName("lineEdit_protocol")
        self.horizontalLayout.addWidget(self.lineEdit_protocol)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_tsteps.setText(_translate("Form", "time step (s)"))
        self.label_nICs.setText(_translate("Form", "# of ICs"))
        self.labe_nclus.setText(_translate("Form", "# of clusters"))
        self.label_tcut.setText(_translate("Form", "time_cutoff (s)"))
        self.lineEdit_tcut.setText(_translate("Form", "10.0"))
        self.lineEdit_tstep.setText(_translate("Form", "0.50"))
        self.label_tstims.setText(_translate("Form", "Stimuli_times (unit:s)"))
        self.lineEdit_numneurons.setText(_translate("Form", "150"))
        self.label_numneurons.setText(_translate("Form", "# of neurons to show"))
        self.pushButton_ica.setText(_translate("Form", "ICA"))
        self.pushButton_kmeans.setText(_translate("Form", "Kmeans"))
        self.pushButton_pcas.setText(_translate("Form", "PCA-sort"))
        self.pushButton_trigger.setText(_translate("Form", "Trigger_filt"))
        self.pushButton_load.setText(_translate("Form", "Load data"))

from matplotlibwidget import MatplotlibWidget
