# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(783, 725)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 80, 551, 106))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_setting = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_setting.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_setting.setObjectName("gridLayout_setting")
        self.label_numneurons = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_numneurons.setObjectName("label_numneurons")
        self.gridLayout_setting.addWidget(self.label_numneurons, 3, 3, 1, 1)
        self.lineEdit_numneurons = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_numneurons.setObjectName("lineEdit_numneurons")
        self.gridLayout_setting.addWidget(self.lineEdit_numneurons, 4, 3, 1, 1)
        self.label_fw = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_fw.setObjectName("label_fw")
        self.gridLayout_setting.addWidget(self.label_fw, 1, 0, 1, 1)
        self.lineEdit_fw = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_fw.setObjectName("lineEdit_fw")
        self.gridLayout_setting.addWidget(self.lineEdit_fw, 2, 0, 1, 1)
        self.label_tsteps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tsteps.setObjectName("label_tsteps")
        self.gridLayout_setting.addWidget(self.label_tsteps, 3, 0, 1, 1)
        self.lineEdit_tstep = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tstep.setObjectName("lineEdit_tstep")
        self.gridLayout_setting.addWidget(self.lineEdit_tstep, 4, 0, 1, 1)
        self.label_tcut = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_tcut.setObjectName("label_tcut")
        self.gridLayout_setting.addWidget(self.label_tcut, 3, 1, 1, 1)
        self.lineEdit_tcut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tcut.setObjectName("lineEdit_tcut")
        self.gridLayout_setting.addWidget(self.lineEdit_tcut, 4, 1, 1, 1)
        self.spinBox_nclus = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_nclus.setMinimum(3)
        self.spinBox_nclus.setObjectName("spinBox_nclus")
        self.gridLayout_setting.addWidget(self.spinBox_nclus, 4, 2, 1, 1)
        self.labe_nclus = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labe_nclus.sizePolicy().hasHeightForWidth())
        self.labe_nclus.setSizePolicy(sizePolicy)
        self.labe_nclus.setObjectName("labe_nclus")
        self.gridLayout_setting.addWidget(self.labe_nclus, 3, 2, 1, 1)
        self.label_nICs = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nICs.sizePolicy().hasHeightForWidth())
        self.label_nICs.setSizePolicy(sizePolicy)
        self.label_nICs.setObjectName("label_nICs")
        self.gridLayout_setting.addWidget(self.label_nICs, 1, 2, 1, 1)
        self.spinBox_nICs = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_nICs.setMinimum(3)
        self.spinBox_nICs.setMaximum(10)
        self.spinBox_nICs.setObjectName("spinBox_nICs")
        self.gridLayout_setting.addWidget(self.spinBox_nICs, 2, 2, 1, 1)
        self.label_vcut = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_vcut.setObjectName("label_vcut")
        self.gridLayout_setting.addWidget(self.label_vcut, 1, 1, 1, 1)
        self.lineEdit_vcut = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vcut.setObjectName("lineEdit_vcut")
        self.gridLayout_setting.addWidget(self.lineEdit_vcut, 2, 1, 1, 1)
        self.spinBox_clse = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_clse.setObjectName("spinBox_clse")
        self.gridLayout_setting.addWidget(self.spinBox_clse, 2, 3, 1, 1)
        self.label_clse = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_clse.setObjectName("label_clse")
        self.gridLayout_setting.addWidget(self.label_clse, 1, 3, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 80, 127, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_btn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_btn.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_btn.setObjectName("verticalLayout_btn")
        self.pushButton_dff = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dff.sizePolicy().hasHeightForWidth())
        self.pushButton_dff.setSizePolicy(sizePolicy)
        self.pushButton_dff.setObjectName("pushButton_dff")
        self.verticalLayout_btn.addWidget(self.pushButton_dff)
        self.pushButton_noise = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_noise.sizePolicy().hasHeightForWidth())
        self.pushButton_noise.setSizePolicy(sizePolicy)
        self.pushButton_noise.setObjectName("pushButton_noise")
        self.verticalLayout_btn.addWidget(self.pushButton_noise)
        self.pushButton_ica = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ica.sizePolicy().hasHeightForWidth())
        self.pushButton_ica.setSizePolicy(sizePolicy)
        self.pushButton_ica.setObjectName("pushButton_ica")
        self.verticalLayout_btn.addWidget(self.pushButton_ica)
        self.pushButton_kmeans = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kmeans.sizePolicy().hasHeightForWidth())
        self.pushButton_kmeans.setSizePolicy(sizePolicy)
        self.pushButton_kmeans.setObjectName("pushButton_kmeans")
        self.verticalLayout_btn.addWidget(self.pushButton_kmeans)
        self.pushButton_pcas = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pcas.sizePolicy().hasHeightForWidth())
        self.pushButton_pcas.setSizePolicy(sizePolicy)
        self.pushButton_pcas.setObjectName("pushButton_pcas")
        self.verticalLayout_btn.addWidget(self.pushButton_pcas)
        self.pushButton_regress = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_regress.sizePolicy().hasHeightForWidth())
        self.pushButton_regress.setSizePolicy(sizePolicy)
        self.pushButton_regress.setObjectName("pushButton_regress")
        self.verticalLayout_btn.addWidget(self.pushButton_regress)
        self.pushButton_regdes = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_regdes.sizePolicy().hasHeightForWidth())
        self.pushButton_regdes.setSizePolicy(sizePolicy)
        self.pushButton_regdes.setObjectName("pushButton_regdes")
        self.verticalLayout_btn.addWidget(self.pushButton_regdes)
        self.pushButton_deln = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deln.sizePolicy().hasHeightForWidth())
        self.pushButton_deln.setSizePolicy(sizePolicy)
        self.pushButton_deln.setObjectName("pushButton_deln")
        self.verticalLayout_btn.addWidget(self.pushButton_deln)
        self.label_figh = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_figh.setObjectName("label_figh")
        self.verticalLayout_btn.addWidget(self.label_figh)
        self.lineEdit_figh = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_figh.setObjectName("lineEdit_figh")
        self.verticalLayout_btn.addWidget(self.lineEdit_figh)
        self.label_figw = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_figw.setObjectName("label_figw")
        self.verticalLayout_btn.addWidget(self.label_figw)
        self.lineEdit_figw = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_figw.setObjectName("lineEdit_figw")
        self.verticalLayout_btn.addWidget(self.lineEdit_figw)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(170, 190, 551, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 531, 381))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_disp = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_disp.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_disp.setObjectName("verticalLayout_disp")
        self.mpl_signal = MatplotlibWidget(self.verticalLayoutWidget_4)
        self.mpl_signal.setObjectName("mpl_signal")
        self.verticalLayout_disp.addWidget(self.mpl_signal)
        self.horizontalLayout_exp = QtWidgets.QHBoxLayout()
        self.horizontalLayout_exp.setObjectName("horizontalLayout_exp")
        self.pushButton_expsig = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_expsig.setObjectName("pushButton_expsig")
        self.horizontalLayout_exp.addWidget(self.pushButton_expsig)
        self.lineEdit_expsig = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_expsig.setObjectName("lineEdit_expsig")
        self.horizontalLayout_exp.addWidget(self.lineEdit_expsig)
        self.verticalLayout_disp.addLayout(self.horizontalLayout_exp)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl_analysis = MatplotlibWidget(self.verticalLayoutWidget)
        self.mpl_analysis.setObjectName("mpl_analysis")
        self.verticalLayout.addWidget(self.mpl_analysis)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_expana = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_expana.setObjectName("pushButton_expana")
        self.horizontalLayout.addWidget(self.pushButton_expana)
        self.lineEdit_expana = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_expana.setObjectName("lineEdit_expana")
        self.horizontalLayout.addWidget(self.lineEdit_expana)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 681, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_loaddata = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loaddata.sizePolicy().hasHeightForWidth())
        self.pushButton_loaddata.setSizePolicy(sizePolicy)
        self.pushButton_loaddata.setObjectName("pushButton_loaddata")
        self.horizontalLayout_3.addWidget(self.pushButton_loaddata)
        self.lineEdit_impdata = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_impdata.setObjectName("lineEdit_impdata")
        self.horizontalLayout_3.addWidget(self.lineEdit_impdata)
        self.pushButton_saveas = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveas.sizePolicy().hasHeightForWidth())
        self.pushButton_saveas.setSizePolicy(sizePolicy)
        self.pushButton_saveas.setObjectName("pushButton_saveas")
        self.horizontalLayout_3.addWidget(self.pushButton_saveas)
        self.lineEdit_expdata = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_expdata.setObjectName("lineEdit_expdata")
        self.horizontalLayout_3.addWidget(self.lineEdit_expdata)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 640, 681, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_indselect = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_indselect.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_indselect.setObjectName("horizontalLayout_indselect")
        self.label_nindex = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_nindex.setObjectName("label_nindex")
        self.horizontalLayout_indselect.addWidget(self.label_nindex)
        self.lineEdit_nindex = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_nindex.setObjectName("lineEdit_nindex")
        self.horizontalLayout_indselect.addWidget(self.lineEdit_nindex)
        self.verticalLayoutWidget_2.raise_()
        self.tabWidget.raise_()
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_numneurons.setText(_translate("Form", "# of neurons to show"))
        self.lineEdit_numneurons.setText(_translate("Form", "200"))
        self.label_fw.setText(_translate("Form", "F0_window"))
        self.label_tsteps.setText(_translate("Form", "time step (s)"))
        self.lineEdit_tstep.setText(_translate("Form", "0.50"))
        self.label_tcut.setText(_translate("Form", "time_cutoff (s)"))
        self.lineEdit_tcut.setText(_translate("Form", "10.0"))
        self.labe_nclus.setText(_translate("Form", "# of clusters"))
        self.label_nICs.setText(_translate("Form", "# of ICs"))
        self.label_vcut.setText(_translate("Form", "var_cut"))
        self.lineEdit_vcut.setText(_translate("Form", "0.95"))
        self.label_clse.setText(_translate("Form", "Choose cluster"))
        self.pushButton_dff.setText(_translate("Form", "Display signal"))
        self.pushButton_noise.setText(_translate("Form", "Noise level"))
        self.pushButton_ica.setText(_translate("Form", "ICA-cluster"))
        self.pushButton_kmeans.setText(_translate("Form", "Kmeans"))
        self.pushButton_pcas.setText(_translate("Form", "PCA-sort"))
        self.pushButton_regress.setText(_translate("Form", "Regression"))
        self.pushButton_regdes.setText(_translate("Form", "Regressor\n"
" Design "))
        self.pushButton_deln.setText(_translate("Form", "Delete neuron(s)"))
        self.label_figh.setText(_translate("Form", "Figure height (in)"))
        self.lineEdit_figh.setText(_translate("Form", "7"))
        self.label_figw.setText(_translate("Form", "Figure width (in)"))
        self.lineEdit_figw.setText(_translate("Form", "7"))
        self.pushButton_expsig.setText(_translate("Form", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Signal cleaning"))
        self.pushButton_expana.setText(_translate("Form", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Clustering"))
        self.pushButton_loaddata.setText(_translate("Form", "Load data"))
        self.lineEdit_impdata.setText(_translate("Form", "/home/sillycat/Programming/Python/dataset/"))
        self.pushButton_saveas.setText(_translate("Form", "Save as..."))
        self.lineEdit_expdata.setText(_translate("Form", "/home/sillycat/Programming/Python/dataset/"))
        self.label_nindex.setText(_translate("Form", "Neuron indices"))

from matplotlibwidget import MatplotlibWidget
