'''
An independent .dax file reader (16-bit big endian) for conveniently reading STORM data in Python scripts.
Adapted by Dan from Zhuang lab's storm-analysis package, datareader.py.
Last update: 10/30/2018.
'''
class DaxReader(Reader):
        """
            Dax reader class. This is a Zhuang lab custom format.
                """
                    def __init__(self, filename, verbose = False):
                                super(DaxReader, self).__init__(filename, verbose = verbose)
                                        
                                                # save the filenames
                                                        dirname = os.path.dirname(filename)
                                                                if (len(dirname) > 0):
                                                                                dirname = dirname + "/"
                                                                                        self.inf_filename = dirname + os.path.splitext(os.path.basename(filename))[0] + ".inf"

                                                                                                # defaults
                                                                                                        self.image_height = None
                                                                                                                self.image_width = None

                                                                                                                        # extract the movie information from the associated inf file
                                                                                                                                size_re = re.compile(r'frame dimensions = ([\d]+) x ([\d]+)')
                                                                                                                                        length_re = re.compile(r'number of frames = ([\d]+)')
                                                                                                                                                endian_re = re.compile(r' (big|little) endian')
                                                                                                                                                        stagex_re = re.compile(r'Stage X = ([\d\.\-]+)')
                                                                                                                                                                stagey_re = re.compile(r'Stage Y = ([\d\.\-]+)')
                                                                                                                                                                        lock_target_re = re.compile(r'Lock Target = ([\d\.\-]+)')
                                                                                                                                                                                scalemax_re = re.compile(r'scalemax = ([\d\.\-]+)')
                                                                                                                                                                                        scalemin_re = re.compile(r'scalemin = ([\d\.\-]+)')

                                                                                                                                                                                                inf_file = open(self.inf_filename, "r")
                                                                                                                                                                                                        while 1:
                                                                                                                                                                                                                        line = inf_file.readline()
                                                                                                                                                                                                                                    if not line: break
                                                                                                                                                                                                                                                m = size_re.match(line)
                                                                                                                                                                                                                                                            if m:
                                                                                                                                                                                                                                                                                self.image_height = int(m.group(2))
                                                                                                                                                                                                                                                                                                self.image_width = int(m.group(1))
                                                                                                                                                                                                                                                                                                            m = length_re.match(line)
                                                                                                                                                                                                                                                                                                                        if m:
                                                                                                                                                                                                                                                                                                                                            self.number_frames = int(m.group(1))
                                                                                                                                                                                                                                                                                                                                                        m = endian_re.search(line)
                                                                                                                                                                                                                                                                                                                                                                    if m:
                                                                                                                                                                                                                                                                                                                                                                                        if m.group(1) == "big":
                                                                                                                                                                                                                                                                                                                                                                                                                self.bigendian = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.bigendian = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    m = stagex_re.match(line)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if m:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.stage_x = float(m.group(1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                m = stagey_re.match(line)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if m:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.stage_y = float(m.group(1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            m = lock_target_re.match(line)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if m:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.lock_target = float(m.group(1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        m = scalemax_re.match(line)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if m:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.scalemax = int(m.group(1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    m = scalemin_re.match(line)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if m:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.scalemin = int(m.group(1))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            inf_file.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # set defaults, probably correct, but warn the user 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # that they couldn't be determined from the inf file.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not self.image_height:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Could not determine image size, assuming 256x256.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.image_height = 256
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.image_width = 256

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # open the dax file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if os.path.exists(filename):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.fileptr = open(filename, "rb")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if self.verbose:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("dax data not found", filename)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def loadAFrame(self, frame_number):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Load a frame & return it as a numpy array.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                super(DaxReader, self).loadAFrame(frame_number)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.fileptr.seek(frame_number * self.image_height * self.image_width * 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                image_data = numpy.fromfile(self.fileptr, dtype='uint16', count = self.image_height * self.image_width)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        image_data = numpy.reshape(image_data, [self.image_height, self.image_width])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if self.bigendian:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                image_data.byteswap(True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return image_data


